default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: juanpardini_development

test:
  <<: *default
  database: juanpardini_test

staging:
  <<: *default
  database: juanpardini_staging

production:
  <<: *default
  database: juanpardini_production
