# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 183c67ac0ee09d6c6c2d773a3f9250a5fa5471850c5a56da73003f69ea4d8310cfdf050d6ed09cfc831f74e1b505096c828f0ef7d465360df6cf3f70774c6ca1

test:
  secret_key_base: 820f2f94f28777c833e33895dd887a590c0112ff47eea50aaa04c59fa00c3038b35255e77360e0ca7d70f503965bb35efb6a081deda119f704e478448ca8b17d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
